### ISSUE TITLE
Add function to determine ceiling

### ISSUE THREAD

**Issue by ollyau** [StevenFrost/AviationWeather#11]
Ceiling is defined as:
- "(Abbrev. CIG) - The height of the cloud base for the lowest broken or overcast cloud layer." (http://forecast.weather.gov/glossary.php?word=CEILING)
- "**Ceiling.** The lowest layer aloft reported as broken or overcast; or the vertical visibility into an
  indefinite ceiling." (http://www.ofcm.gov/fmh-1/pdf/I-CH9.pdf)
- "_Ceiling_ means the height above the earth's surface of the lowest layer of clouds or obscuring phenomena that is reported as “broken”, “overcast”, or “obscuration”, and not classified as “thin” or “partial”." (https://www.law.cornell.edu/cfr/text/14/1.1).

We can determine the ceiling given a METAR by looking at its `sky_condition_group` vector.  Example function prototype below:

`cloud_layer get_ceiling() const;`

**Comment by StevenFrost** [comment]
Fixed in #18
